name: Setup Python Project
description: Setup Python and uv

inputs:
  python-version:
    description: Python version
    required: true

runs:
  using: composite
  steps:
    - uses: astral-sh/setup-uv@v6

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install app dependencies
      shell: bash
      working-directory: ./backend
      run: uv sync