"""Public exports for the accounts package.

Prefer importing account domain objects from here instead of reaching into service,
model, schema, or exception modules directly.
"""

from backend.accounts.exceptions import (
    AuthDatabaseError,
    AuthError,
    AuthExternalServiceError,
    AuthValidationError,
    FirebaseUserError,
    InstitutionAssignmentError,
    InstitutionCreateError,
    InstitutionError,
    InstitutionNotFound,
    InstitutionReadError,
    InstitutionSeedError,
    InstitutionValidationError,
    UserCreateError,
    UserDeleteError,
    UserError,
    UserNotFound,
    UserReadError,
    UserUpdateError,
    UserValidationError,
)
from backend.accounts.institutions import InstitutionDB
from backend.accounts.model import Institution, Role, User, UserRoleLink
from backend.accounts.schemas import (
    CreateUserFullPayload,
    InstitutionRead,
    UpdateUserInstitution,
    UserBase,
    UserCreate,
    UserDetailRead,
    UserInstResponse,
    UserRead,
    UserUpdate,
    ValidInstitutions,
)
from backend.accounts.users import UserDB, UserManager
from backend.authorization.roles.repository import RoleDB
from backend.authorization.roles import  RoleRead, UpdateUserRole, UserRoles
from backend.authorization.roles.exceptions import (
    RoleAssignmentError,
    RoleCreateError,
    RoleError,
    RoleNotFound,
    RoleReadError,
    RoleSeedError,
)

__all__ = [
    "AuthDatabaseError",
    "AuthError",
    "AuthExternalServiceError",
    "AuthValidationError",
    "CreateUserFullPayload",
    "FirebaseUserError",
    "Institution",
    "InstitutionAssignmentError",
    "InstitutionCreateError",
    "InstitutionDB",
    "InstitutionError",
    "InstitutionNotFound",
    "InstitutionRead",
    "InstitutionReadError",
    "InstitutionSeedError",
    "InstitutionValidationError",
    "Role",
    "RoleAssignmentError",
    "RoleCreateError",
    "RoleDB",
    "RoleError",
    "RoleNotFound",
    "RoleRead",
    "RoleReadError",
    "RoleSeedError",
    "UpdateUserInstitution",
    "UpdateUserRole",
    "User",
    "UserBase",
    "UserCreate",
    "UserCreateError",
    "UserDB",
    "UserDeleteError",
    "UserDetailRead",
    "UserError",
    "UserInstResponse",
    "UserManager",
    "UserNotFound",
    "UserRead",
    "UserReadError",
    "UserRoleLink",
    "UserRoles",
    "UserUpdate",
    "UserUpdateError",
    "UserValidationError",
    "ValidInstitutions",
]
