name: Setup Python Project

runs:
  using: composite
  strategy:
    matrix:
      python-version: [3.11, 3.12, 3.13]

    env:
      ENV: "testing"

  steps:
    - uses: astral-sh/setup-uv@v6

    - uses: actions/setup-python@v5
    - name: Install Python Dependencies
      with:
        python-version: ${{matrix.python-version}}

    # Install uv
    - name: Install uv
        run: |
        python -m pip intall --upgrade pip
        pip install uv
    - name: Install app dependencies
        working-direcotory: ./backend
        run: uv sync
        
