"""Defined question collection model

Revision ID: 045e23037f8a
Revises: aa4da4b641e1
Create Date: 2026-07-29 13:45:05.282011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '045e23037f8a'
down_revision: Union[str, Sequence[str], None] = 'aa4da4b641e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_collection',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['developer_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_collection', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_collection_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_collection_title'), ['title'], unique=False)

    op.create_table('question_collection_link',
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('collection_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['question_collection.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('question_id', 'collection_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_collection_link')
    with op.batch_alter_table('question_collection', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_collection_title'))
        batch_op.drop_index(batch_op.f('ix_question_collection_id'))

    op.drop_table('question_collection')
    # ### end Alembic commands ###
