"""added cascading delete on source question table on deletion of question id

Revision ID: 09a1ca6f8218
Revises: adcb2fca953e
Create Date: 2026-08-27 16:24:03.574251

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09a1ca6f8218"
down_revision: str | Sequence[str] | None = "adcb2fca953e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_source_reference", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_source_reference_question_id"))
        batch_op.drop_constraint(
            batch_op.f("question_source_reference_question_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "question", ["question_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_source_reference", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("question_source_reference_question_id_fkey"),
            "question",
            ["question_id"],
            ["id"],
        )
        batch_op.create_index(
            batch_op.f("ix_question_source_reference_question_id"),
            ["question_id"],
            unique=False,
        )

    # ### end Alembic commands ###
