"""Added Collection Dashboard

Revision ID: 11e3ada97f8a
Revises: f4f353fa4d1f
Create Date: 2026-08-06 12:01:01.953423

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11e3ada97f8a"
down_revision: str | Sequence[str] | None = "f4f353fa4d1f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

query = """
CREATE OR REPLACE VIEW dashboard_with_collections AS
SELECT
    qt.*,
    qcl.collection_id,
    qc.title as "collection_title"
FROM
    question_table_view qt
    LEFT JOIN question_collection_link qcl ON qcl.question_id = qt.question_id
    LEFT JOIN question_collection qc ON qcl.collection_id = qc.id
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS dashboard_with_collections;")
    op.execute(query)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS dashboard_with_collections;")
    # ### end Alembic commands ###
