"""Updated the question table view

Revision ID: 1dca84023711
Revises: 4364ba6530ef
Create Date: 2026-08-06 18:27:15.887254

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1dca84023711"
down_revision: str | Sequence[str] | None = "4364ba6530ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'question_table_view'
          AND column_name = 'owner_id'
    ) THEN
        ALTER VIEW question_table_view RENAME COLUMN owner_id TO user_id;
    END IF;
END $$;
""")


op.execute("""
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'dashboard_with_collections'
          AND column_name = 'owner_id'
    ) THEN
        ALTER VIEW dashboard_with_collections RENAME COLUMN owner_id TO user_id;
    END IF;
END $$;
""")
# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
