from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy import inspect
from sqlalchemy.dialects import postgresql

revision: str = "2acf7d5a14dc"
down_revision: str | Sequence[str] | None = "5b0929781b0d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [
        column["name"] for column in inspector.get_columns("question_collection")
    ]

    with op.batch_alter_table(
        "question_collection",
        schema=None,
    ) as batch_op:
        if "customization" in columns:
            batch_op.drop_column("customization")
        if "description" in columns:
            batch_op.drop_column("description")

    with op.batch_alter_table("question_collection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "customization",
                postgresql.JSONB(astext_type=sa.Text()),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = inspect(conn)
    columns = [
        column["name"] for column in inspector.get_columns("question_collection")
    ]

    with op.batch_alter_table(
        "question_collection",
        schema=None,
    ) as batch_op:
        if "customization" in columns:
            batch_op.drop_column("customization")
        if "description" in columns:
            batch_op.drop_column("description")
    # ### end Alembic commands ###
