"""RRemoved the extra fileds for the user

Revision ID: 40572f937b8b
Revises: 4a90636569f4
Create Date: 2025-11-29 14:27:48.275793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40572f937b8b'
down_revision: Union[str, Sequence[str], None] = '4a90636569f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('educatorprofile')
    op.drop_table('studenprofile')
    op.drop_table('developerprofile')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('institution', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('institution')

    op.create_table('developerprofile',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('studenprofile',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('institution', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('educatorprofile',
    sa.Column('user_id', sa.CHAR(length=32), nullable=False),
    sa.Column('institution', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###
