"""Added tighter constraint to database

Revision ID: 4364ba6530ef
Revises: 11e3ada97f8a
Create Date: 2026-08-06 16:49:40.048967

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4364ba6530ef"
down_revision: str | Sequence[str] | None = "11e3ada97f8a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "question_attempt_link",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("quiz_data", sa.JSON(), nullable=False),
        sa.Column("submitted_answer", sa.JSON(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "attemption_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id", "question_id", "user_id"),
        if_not_exists=True
        
    )
    with op.batch_alter_table("question_attempt_link", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_attempt_link_id"),
            ["id"],
            unique=False,
            if_not_exists=True,
        )
    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("message_thread_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "thread", ["thread_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("thread_user_id_fkey"), type_="foreignkey")
        batch_op.create_foreign_key(
            None, "user", ["user_id"], ["id"], ondelete="CASCADE"
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=False)

    with op.batch_alter_table("thread", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("thread_user_id_fkey"), "user", ["user_id"], ["id"]
        )

    with op.batch_alter_table("message", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("message_thread_id_fkey"), "thread", ["thread_id"], ["id"]
        )

    with op.batch_alter_table("question_attempt_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_attempt_link_id"))

    op.drop_table("question_attempt_link")
    # ### end Alembic commands ###
