"""Added granted by id to both the collection and question access to determine who you shared it with

Revision ID: 4661f322f26a
Revises: ab37708929c4
Create Date: 2026-08-12 13:54:45.959034

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4661f322f26a"
down_revision: str | Sequence[str] | None = "ab37708929c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_access", schema=None) as batch_op:
        batch_op.add_column(sa.Column("granted_by_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            None, "developer_profile", ["granted_by_id"], ["id"]
        )

    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.add_column(sa.Column("granted_by_id", sa.Uuid(), nullable=True))
        batch_op.create_foreign_key(
            None, "developer_profile", ["granted_by_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("granted_by_id")

    with op.batch_alter_table("question_access", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("granted_by_id")

    # ### end Alembic commands ###
