"""Added question status and added user roles to the models

Revision ID: 4a90636569f4
Revises: 214cef820d4c
Create Date: 2025-11-29 13:19:21.928466

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4a90636569f4"
down_revision: Union[str, Sequence[str], None] = "214cef820d4c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question", schema=None) as batch_op:
        question_status = sa.Enum("PUBLIC", "PRIVATE", name="questionstatus")
        question_status.create(op.get_bind(), checkfirst=True)
        batch_op.add_column(sa.Column("status", question_status, nullable=True))

    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.execute("UPDATE question SET status = 'PUBLIC' WHERE status IS NULL")
    with op.batch_alter_table("question") as batch_op:
        batch_op.alter_column("status", existing_type=question_status, nullable=False)
    with op.batch_alter_table("studenprofile", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("institution", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
        )

    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("storage_path")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("storage_path", sa.VARCHAR(), nullable=True))

    with op.batch_alter_table("studenprofile", schema=None) as batch_op:
        batch_op.drop_column("institution")

    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.drop_column("status")

    # ### end Alembic commands ###
