"""Added parson question type

Revision ID: 5b0929781b0d
Revises: 09a1ca6f8218
Create Date: 2026-08-31 13:37:30.399238

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5b0929781b0d"
down_revision: Union[str, Sequence[str], None] = "09a1ca6f8218"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


CREATE_QUESTION_TABLE_VIEW_SQL = """
DROP VIEW IF EXISTS question_table_view;

CREATE VIEW
    question_table_view AS
SELECT
    "question"."id" AS "question_id",
    "developer_profile"."user_id" AS "user_id",
    "developer_profile"."id" AS "developer_profile_id",
    "question"."title",
    "institution"."id" AS "institution_id",
    "institution"."name" AS "institution",
    "user"."email" AS "created_by",
    "question"."isAdaptive",
    "question"."status",
    array_agg(DISTINCT "topic"."name"::text ORDER BY "topic"."name"::text) AS "topics",

array_agg(
    DISTINCT "question_type"."name"::text
    ORDER BY "question_type"."name"::text
) AS "question_type",

coalesce(
    array_agg(
        DISTINCT "question_runtime"."language"::text
        ORDER BY "question_runtime"."language"::text
    ) FILTER (WHERE "question_runtime"."language" IS NOT NULL),
    ARRAY[]::text[]
) AS "available_runtimes",
    "question"."created_at",
    "question"."updated_at"
FROM
    "question"
    LEFT JOIN "question_topic_link" ON "question_topic_link"."question_id" = "question"."id"
    LEFT JOIN "topic" ON "topic"."id" = "question_topic_link"."topic_id"
    LEFT JOIN  "question_qtype_link" ON "question_qtype_link"."question_id" = "question"."id"
    LEFT JOIN  "question_type" ON "question_type"."id" = "question_qtype_link"."qtype_id"
    LEFT JOIN "question_runtime" ON "question_runtime"."question_id" = "question"."id"
    JOIN "developer_profile" ON "developer_profile"."id" = "question"."created_by_id"
    JOIN "user" ON "user"."id" = "developer_profile"."user_id"
    LEFT JOIN "institution" ON "user"."institution_id" = "institution"."id"
GROUP BY
    "question"."id",
    "developer_profile"."user_id",
    "developer_profile"."id",
    "question"."title",
    "institution"."id",
    "institution"."name",
    "user"."email",
    "question"."status",
    "question"."created_at",
    "question"."updated_at";
    """
CREATE_DASHBOARD_WITH_COLLECTIONS_SQL = """
DROP VIEW IF EXISTS dashboard_with_collections;

CREATE VIEW
    dashboard_with_collections AS
SELECT
    qt.*,
    qcl.collection_id,
    qc.title as "collection_title"
FROM
    question_table_view qt
    LEFT JOIN question_collection_link qcl ON qcl.question_id = qt.question_id
    LEFT JOIN question_collection qc ON qcl.collection_id = qc.id;
"""


old_qtype = postgresql.ENUM(
    "MC",
    "MCQ",
    "MA",
    "TF",
    "FB",
    "NUM",
    name="qtype",
)

new_qtype = postgresql.ENUM(
    "mc",
    "mcq",
    "ma",
    "tf",
    "fb",
    "num",
    "parsons",
    "multi",
    name="qtype_enum",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW IF EXISTS dashboard_with_collections;")
    op.execute("DROP VIEW IF EXISTS question_table_view;")

    bind = op.get_bind()
    new_qtype.create(bind, checkfirst=True)

    with op.batch_alter_table("question_type", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=old_qtype,
            type_=new_qtype,
            existing_nullable=False,
            postgresql_using="lower(name::text)::qtype_enum",
        )
    op.execute(CREATE_QUESTION_TABLE_VIEW_SQL)
    op.execute(CREATE_DASHBOARD_WITH_COLLECTIONS_SQL)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS dashboard_with_collections;")
    op.execute("DROP VIEW IF EXISTS question_table_view;")

    op.execute("""DELETE FROM question_qtype_link
        WHERE qtype_id IN (
        SELECT id
        FROM question_type
        WHERE name::text = 'parsons'
        );
        DELETE FROM question_type WHERE name::text = 'parsons'""")
    op.execute("""DELETE FROM question_qtype_link
        WHERE qtype_id IN (
        SELECT id
        FROM question_type
        WHERE name::text = 'multi'
        );
        DELETE FROM question_type WHERE name::text = 'multi'""")

    bind = op.get_bind()
    old_qtype.create(bind, checkfirst=True)

    with op.batch_alter_table("question_type", schema=None) as batch_op:

        batch_op.alter_column(
            "name",
            existing_type=new_qtype,
            type_=old_qtype,
            existing_nullable=False,
            postgresql_using="upper(name::text)::qtype",
        )

    new_qtype.drop(bind, checkfirst=True)

    op.execute(CREATE_QUESTION_TABLE_VIEW_SQL)
    op.execute(CREATE_DASHBOARD_WITH_COLLECTIONS_SQL)
