"""Added question access model

Revision ID: 7459cfdc11a3
Revises: b6241999eca7
Create Date: 2026-07-31 13:41:10.242376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7459cfdc11a3'
down_revision: Union[str, Sequence[str], None] = 'b6241999eca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_access',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('developer_id', sa.Uuid(), nullable=False),
    sa.Column('access_level', sa.Enum('VIEW', 'EDIT', 'FULL', name='accesslevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['developer_id'], ['developer_profile.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_access', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_access_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_access', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_access_id'))

    op.drop_table('question_access')
    # ### end Alembic commands ###
