"""candidate initial schema

Revision ID: 7a80075e0e41
Revises:
Create Date: 2026-08-06 16:09:35.887474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7a80075e0e41"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "institution",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            sa.Enum("UCR", "CPP", "NORCO", name="validinstitutions"),
            nullable=False,
        ),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question_type",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "name",
            sa.Enum("MC", "MCQ", "MA", "TF", "FB", "NUM", name="qtype"),
            nullable=False,
        ),
        sa.Column("display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_type", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_type_name"), ["name"], unique=True
        )

    op.create_table(
        "role",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_role_name"), ["name"], unique=False)

    op.create_table(
        "topic",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_topic_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_topic_name"), ["name"], unique=True)

    op.create_table(
        "user",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("username", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("institution_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(
            ["institution_id"],
            ["institution.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "developer_profile",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("storage_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "thread",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_role_link",
        sa.Column("role_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "user_id"),
    )
    op.create_table(
        "message",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("thread_id", sa.Uuid(), nullable=False),
        sa.Column("role", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "content",
            sa.JSON().with_variant(
                postgresql.JSONB(astext_type=sa.Text()), "postgresql"
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["thread_id"], ["thread.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "question",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("isAdaptive", sa.Boolean(), nullable=False),
        sa.Column("ai_generated", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("ARCHIVED", "DRAFT", "PUBLISHED", name="status"),
            server_default="DRAFT",
            nullable=False,
        ),
        sa.Column("storage_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("storage_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("created_by_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by_id"],
            ["developer_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_question_id"), ["id"], unique=False)
        batch_op.create_index(batch_op.f("ix_question_title"), ["title"], unique=False)

    op.create_table(
        "question_collection",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("parent_id", sa.Uuid(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["developer_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["question_collection.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("question_collection", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_collection_id"), ["id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_collection_parent_id"), ["parent_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_question_collection_title"), ["title"], unique=False
        )

    op.create_table(
        "question_access",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("developer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum("VIEW", "EDIT", "FULL", "OWNER", name="accesslevel"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["developer_id"],
            ["developer_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "question_id", "developer_id", name="uq_question_access_question_developer"
        ),
    )
    with op.batch_alter_table("question_access", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_question_access_id"), ["id"], unique=False)
        batch_op.create_index(
            "uq_question_access_one_owner_per_question",
            ["question_id"],
            unique=True,
            sqlite_where=sa.text("access_level = 'OWNER'"),
            postgresql_where="access_level = 'OWNER'",
        )

    op.create_table(
        "question_attempt_link",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("quiz_data", sa.JSON(), nullable=False),
        sa.Column("submitted_answer", sa.JSON(), nullable=False),
        sa.Column("is_correct", sa.Boolean(), nullable=False),
        sa.Column(
            "attemption_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id", "question_id", "user_id"),
    )
    with op.batch_alter_table("question_attempt_link", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_attempt_link_id"), ["id"], unique=False
        )

    op.create_table(
        "question_collection_access",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("developer_id", sa.Uuid(), nullable=False),
        sa.Column(
            "access_level",
            sa.Enum("VIEW", "EDIT", "FULL", "OWNER", name="accesslevel"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["question_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["developer_id"],
            ["developer_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_id",
            "developer_id",
            name="uq_question_collection_access_collection_developer",
        ),
    )
    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_collection_access_id"), ["id"], unique=False
        )
        batch_op.create_index(
            "uq_question_collection_access_one_owner_per_collection",
            ["collection_id"],
            unique=True,
            sqlite_where=sa.text("access_level = 'OWNER'"),
            postgresql_where=sa.text("access_level = 'OWNER'"),
        )

    op.create_table(
        "question_collection_link",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["question_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "collection_id"),
    )
    op.create_table(
        "question_qtype_link",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("qtype_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["qtype_id"],
            ["question_type.id"],
        ),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "qtype_id"),
    )
    op.create_table(
        "question_runtime",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column(
            "language",
            sa.Enum("JAVASCRIPT", "PYTHON", name="runtimelanguage"),
            nullable=False,
        ),
        sa.Column("entry", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("func_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("MANUAL", "CONFIG_FILE", "INFERRED", name="runtimeconfigsource"),
            nullable=False,
        ),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "question_id", "language", name="uq_question_runtime_language"
        ),
    )
    with op.batch_alter_table("question_runtime", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_runtime_language"), ["language"], unique=False
        )
        batch_op.create_index(
            "uq_question_runtime_default_enabled",
            ["question_id"],
            unique=True,
            postgresql_where=sa.text("is_default=true AND enabled = true"),
            sqlite_where=sa.text("is_default = 1 AND enabled = 1"),
        )

    op.create_table(
        "question_topic_link",
        sa.Column("question_id", sa.Uuid(), nullable=False),
        sa.Column("topic_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["question_id"],
            ["question.id"],
        ),
        sa.ForeignKeyConstraint(
            ["topic_id"],
            ["topic.id"],
        ),
        sa.PrimaryKeyConstraint("question_id", "topic_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("question_topic_link")
    with op.batch_alter_table("question_runtime", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_question_runtime_default_enabled",
            postgresql_where=sa.text("is_default=true AND enabled = true"),
            sqlite_where=sa.text("is_default = 1 AND enabled = 1"),
        )
        batch_op.drop_index(batch_op.f("ix_question_runtime_language"))

    op.drop_table("question_runtime")
    op.drop_table("question_qtype_link")
    op.drop_table("question_collection_link")
    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_question_collection_access_one_owner_per_collection",
            sqlite_where=sa.text("access_level = 'OWNER'"),
            postgresql_where=sa.text("access_level = 'OWNER'"),
        )
        batch_op.drop_index(batch_op.f("ix_question_collection_access_id"))

    op.drop_table("question_collection_access")
    with op.batch_alter_table("question_attempt_link", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_attempt_link_id"))

    op.drop_table("question_attempt_link")
    with op.batch_alter_table("question_access", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_question_access_one_owner_per_question",
            sqlite_where=sa.text("access_level = 'OWNER'"),
            postgresql_where="access_level = 'OWNER'",
        )
        batch_op.drop_index(batch_op.f("ix_question_access_id"))

    op.drop_table("question_access")
    with op.batch_alter_table("question_collection", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_collection_title"))
        batch_op.drop_index(batch_op.f("ix_question_collection_parent_id"))
        batch_op.drop_index(batch_op.f("ix_question_collection_id"))

    op.drop_table("question_collection")
    with op.batch_alter_table("question", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_title"))
        batch_op.drop_index(batch_op.f("ix_question_id"))

    op.drop_table("question")
    op.drop_table("message")
    op.drop_table("user_role_link")
    op.drop_table("thread")
    op.drop_table("developer_profile")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    with op.batch_alter_table("topic", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_topic_name"))
        batch_op.drop_index(batch_op.f("ix_topic_id"))

    op.drop_table("topic")
    with op.batch_alter_table("role", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_role_name"))

    op.drop_table("role")
    with op.batch_alter_table("question_type", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_question_type_name"))

    op.drop_table("question_type")
    op.drop_table("institution")
    # ### end Alembic commands ###
