"""Added Question Source reference for legacy

Revision ID: a68ddff5e0ea
Revises: 4661f322f26a
Create Date: 2026-08-25 14:02:43.983725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a68ddff5e0ea'
down_revision: Union[str, Sequence[str], None] = '4661f322f26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_source_reference',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('question_id', sa.Uuid(), nullable=False),
    sa.Column('source_question_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('raw_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_id', 'source_question_id', name='uq_question_source_reference_source_question')
    )
    with op.batch_alter_table('question_source_reference', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_source_reference_question_id'), ['question_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_question_source_reference_source_question_id'), ['source_question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_source_reference', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_source_reference_source_question_id'))
        batch_op.drop_index(batch_op.f('ix_question_source_reference_question_id'))

    op.drop_table('question_source_reference')
    # ### end Alembic commands ###
