"""Added cascading delete to quesiton access on question delete

Revision ID: ab37708929c4
Revises: fdd4aab54281
Create Date: 2026-08-11 15:42:54.973864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ab37708929c4'
down_revision: Union[str, Sequence[str], None] = 'fdd4aab54281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_access', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_access_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_access', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_access_question_id_fkey'), 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###
