"""added cascading delete on runtime when question is deleted

Revision ID: adcb2fca953e
Revises: a68ddff5e0ea
Create Date: 2026-08-27 16:22:20.830875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'adcb2fca953e'
down_revision: Union[str, Sequence[str], None] = 'a68ddff5e0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_runtime', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('question_runtime_question_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_runtime', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('question_runtime_question_id_fkey'), 'question', ['question_id'], ['id'])

    # ### end Alembic commands ###
