"""Added a unique constraint to the access level to ensure each user only only has one access level,and a unique constraint such that there is only one owner per question, additionally added a new enum value

Revision ID: b06880a9eb08
Revises: 7459cfdc11a3
Create Date: 2026-08-03 13:57:54.274047

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b06880a9eb08"
down_revision: str | Sequence[str] | None = "7459cfdc11a3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    if bind.dialect.name == "postgresql":
        with op.get_context().autocommit_block():
            op.execute("ALTER TYPE accesslevel ADD VALUE IF NOT EXISTS 'OWNER'")

    with op.batch_alter_table("question_access", schema=None) as batch_op:
        batch_op.create_index(
            "uq_question_access_one_owner_per_question",
            ["question_id"],
            unique=True,
            postgresql_where="access_level = 'OWNER'",
        )
        batch_op.create_unique_constraint(
            "uq_question_access_question_developer", ["question_id", "developer_id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_access", schema=None) as batch_op:
        batch_op.drop_constraint(
            "uq_question_access_question_developer", type_="unique"
        )
        batch_op.drop_index(
            "uq_question_access_one_owner_per_question",
            postgresql_where="access_level = 'owner'",
        )

    # ### end Alembic commands ###
