"""Defined question collection parent id

Revision ID: b6241999eca7
Revises: 045e23037f8a
Create Date: 2026-07-29 14:15:54.181486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b6241999eca7'
down_revision: Union[str, Sequence[str], None] = '045e23037f8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_id', sa.Uuid(), nullable=True))
        batch_op.create_index(batch_op.f('ix_question_collection_parent_id'), ['parent_id'], unique=False)
        batch_op.create_foreign_key(None, 'question_collection', ['parent_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_collection', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_question_collection_parent_id'))
        batch_op.drop_column('parent_id')

    # ### end Alembic commands ###
