"""Added status field to collection

Revision ID: e59dc78510a4
Revises: 2acf7d5a14dc
Create Date: 2026-09-14 16:14:01.309596

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e59dc78510a4"
down_revision: Union[str, Sequence[str], None] = "2acf7d5a14dc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status",
                sa.Enum("ARCHIVED", "DRAFT", "PUBLISHED", name="status"),
                nullable=True,
            )
        )

        batch_op.alter_column(
            "customization",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )
    op.execute("""
            UPDATE question_collection SET status='DRAFT' WHERE status is NULL;""")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection", schema=None) as batch_op:
        batch_op.alter_column(
            "customization",
            existing_type=postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        )
        batch_op.drop_column("status")

    # ### end Alembic commands ###
