"""Added cascading delete on question collection when collection ro question is deleted

Revision ID: e71f478f0d0a
Revises: 1dca84023711
Create Date: 2026-08-07 16:14:31.912019

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e71f478f0d0a"
down_revision: str | Sequence[str] | None = "1dca84023711"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection_link", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("question_collection_link_collection_id_fkey"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("question_collection_link_question_id_fkey"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            None, "question_collection", ["collection_id"], ["id"], ondelete="CASCADE"
        )
        batch_op.create_foreign_key(
            None, "question", ["question_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection_link", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("question_collection_link_question_id_fkey"),
            "question",
            ["question_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("question_collection_link_collection_id_fkey"),
            "question_collection",
            ["collection_id"],
            ["id"],
        )

    # ### end Alembic commands ###
