"""Added the question collection access

Revision ID: f4f353fa4d1f
Revises: b06880a9eb08
Create Date: 2026-08-04 18:53:23.507086

"""

from typing import Sequence, Union
from sqlalchemy.dialects import postgresql
from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "f4f353fa4d1f"
down_revision: Union[str, Sequence[str], None] = "b06880a9eb08"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    access_level_enum = postgresql.ENUM(
        "VIEW",
        "EDIT",
        "FULL",
        "OWNER",
        name="accesslevel",
        create_type=False,
    )
    op.create_table(
        "question_collection_access",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("collection_id", sa.Uuid(), nullable=False),
        sa.Column("developer_id", sa.Uuid(), nullable=False),
        sa.Column("access_level", access_level_enum, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["question_collection.id"],
        ),
        sa.ForeignKeyConstraint(
            ["developer_id"],
            ["developer_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "collection_id",
            "developer_id",
            name="uq_question_collection_access_collection_developer",
        ),
    )
    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_question_collection_access_id"), ["id"], unique=False
        )
        batch_op.create_index(
            "uq_question_collection_access_one_owner_per_collection",
            ["collection_id"],
            unique=True,
            sqlite_where=sa.text("access_level = 'OWNER'"),
            postgresql_where=sa.text("access_level = 'OWNER'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_question_collection_access_one_owner_per_collection",
            sqlite_where=sa.text("access_level = 'OWNER'"),
            postgresql_where=sa.text("access_level = 'OWNER'"),
        )
        batch_op.drop_index(batch_op.f("ix_question_collection_access_id"))

    op.drop_table("question_collection_access")
    # ### end Alembic commands ###
