"""Added cascading delete on question collection access

Revision ID: fdd4aab54281
Revises: e71f478f0d0a
Create Date: 2026-08-07 16:16:17.997025

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fdd4aab54281"
down_revision: str | Sequence[str] | None = "e71f478f0d0a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("question_collection_access_collection_id_fkey"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            None, "question_collection", ["collection_id"], ["id"], ondelete="CASCADE"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_collection_access", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("question_collection_access_collection_id_fkey"),
            "question_collection",
            ["collection_id"],
            ["id"],
        )

    # ### end Alembic commands ###
