name: Backend API Startup
# Only triggers if there is a backend change
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    env:
      ENV: testing
      STORAGE_BUCKET: ${{secrets.STORAGE_BUCKET}}
      FIREBASE_CRED: ${{vars.FIREBASE_JSON_PATH}}
      FIREBASE_AUTH_EMULATOR_HOST: 127.0.0.1:9099
      STORAGE_EMULATOR_HOST: http://localhost:9199
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-backend
        with:
          python-version: ${{ matrix.python-version }}

      - uses: ./.github/actions/firebase-credentials
        with:
          firebase-json: ${{ secrets.FIREBASE_JSON }}
          credentials-path: ${{ vars.FIREBASE_JSON_PATH }}

      - name: Run Test
        run: |
          uv run pytest app_test/unit
        working-directory: ./backend
