name: Backend API Startup
# Only triggers if there is a backend change
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12, 3.13]

    env:
      ENV: testing
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./github/actions/setup-backend
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run Test
        run: |
          uv run pytest app_test/unit
        working-directory: ./backend
