name: Backend API Startup
# Only triggers if there is a backend change
on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: ./github/actions/setup-backend

      - name: Run Test
        run: |
          uv run pytest app_test/unit
        working-directory: ./backend
